[package]
name = "cuslip"
version = "0.1.0"
authors = ["theJPster <github@thejpster.org.uk>"]

[[bin]]
name = "example"
doc = false

[dependencies]
log = "0.3"
env_logger = "0.3"
time = "0.1"
mio = "0.5"
