[package]
name = "grease"
version = "0.5.0"
authors = ["theJPster <github@thejpster.org.uk>"]
readme = "README.md"

[dev-dependencies]
env_logger = "0.5.6"
time = "0.1"
log = "0.4.1"

[dependencies]
grease-socket = { path = "socket" }
grease-types = { path = "types" }

[workspace]
