[package]
name = "grease-workspace"
version = "0.1.0"
authors = ["Jonathan Pallant <jonathan.pallant@cambridgeconsultants.com>"]
readme = "README.md"
license-file = "COPYRIGHT"

[workspace]
members = [
	"grease",
	"grease-socket",
	"grease-http",
]
