[package]
name = "grease-workspace"
version = "0.1.0"
authors = ["theJPster <github@thejpster.org.uk>"]
readme = "README.md"

[dev-dependencies]
env_logger = "0.5.6"
log = "0.4.1"

[dependencies]
grease-socket = { path = "./grease-socket" }
grease-http = { path = "./grease-http" }
grease = { path = "./grease" }

[workspace]
