[package]
name = "grease-socket"
version = "0.1.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]

[dependencies]
mio = "0.6"
mio-more = "0.1.0"
grease = { path = "../grease" }
log = "0.4.1"
rand = "0.4.2"
